language: node_js
dist: focal
node_js:
  - 10
  - 12
  - 14
  - 15

script:
  - npm run lint
  - npm test

jobs:
  include:
    - stage: release to npm
      if: tag IS present
      script: npm run build
      before_deploy: cd dist
      deploy:
        on:
          tags: true
        provider: npm
        edge: true
        email: $NPM_EMAIL_ADDRESS
        api_key: $NPM_AUTH_TOKEN
